version:  '3.8'
services:
  node_app:
    build : .
    ports:
      - "3000:3000"
    networks:
      - monitoring
  
  prometheus:
    image : prom/prometheus:latest
    volumes:
      - "./:/etc/prometheus"
    ports:
      - "9090:9090"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
  
networks: 
  monitoring: